version: '3'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.5.2
    container_name: logstash
    restart: always
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - elastic-stack
    environment:
      - xpack.monitoring.enabled=false
      - log.level=warn
      - config.reload.automatic=true
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: always
    networks:
      - elastic-stack
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    container_name: kibana
    volumes:
     - ./kibana/config/:/usr/share/kibana/config
    restart: always
    depends_on: 
      - elasticsearch
    ports: 
      - 5601:5601
    networks:
      - elastic-stack

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.5.2
    container_name: apm
    volumes: 
      - ./apm-server/:/usr/share/apm-server/apm-server.yml
    depends_on: 
      - elasticsearch
    networks:
      - elastic-stack

networks:
  elastic-stack:
    driver: bridge
  

volumes:
  esdata:
    driver: local