## Save in: kibana/config/kibana.yml
# Default Kibana configuration from kibana-docker.

server.name: kibana
server.host: "0.0.0.0"
#elasticsearch.url: http://elasticsearch:9200
#elasticsearch.username: admin
#elasticsearch.password: admin
elasticsearch.hosts: http://elasticsearch:9200
xpack.security.enabled: false
server.port: 5601
kibana.index: ".kibana"
#elasticsearch.url: "http://127.0.0.1:9200"